#Liste des commandes
commands:
  shop:
    command: "zshop" #Default commande
    aliases: #Aliases
      - "shop"
      - "myshop" 
    inventory: "shop" #File name

  blocks:
    command: "blocks" #Default commande
    aliases: #Aliases
      - "block"
      - "b" 
    inventory: "blocks" #File name    
    
#Liste des catégories à charger, le fichier doit être dans le dossier inventories.
# Vous ne devez pas mettre une catégories qui est déjà chargé !
categories:    
 - "ores"
 - "redstone"
 - "farm"
 - "foods"
 - "miscellaneous"
 - "mobs"