name: zShop
author: Maxlego08
main: fr.maxlego08.shop.ZShop
version: 2.0.2.4
api-version: 1.13
softdepend: [Vault, MySQL-Tokens, TokenManager, PlayerPoints, HeadDatabase, PlaceholderAPI, zSpawner, EpicHeads, CataEssentials]
commands:
