#########################################################################################################################################
#
#  ███████╗░██████╗██╗░░██╗░█████╗░██████╗░
#  ╚════██║██╔════╝██║░░██║██╔══██╗██╔══██╗
#  ░░███╔═╝╚█████╗░███████║██║░░██║██████╔╝
#  ██╔══╝░░░╚═══██╗██╔══██║██║░░██║██╔═══╝░
#  ███████╗██████╔╝██║░░██║╚█████╔╝██║░░░░░
#  ╚══════╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░
#
#########################################################################################################################################

defaultLore:
  - "&f» &7Buying price&8: &e%buyPrice%"
  - "&f» &7Selling price&8: &e%sellPrice%"
  - ""
  - "&f➥ &r&7Left click to &f&nʙᴜʏ"
  - "&f➥ &r&7Click wheel (or drop key) to &f&nsᴇʟʟ ᴇᴠᴇʀʏᴛʜɪɴɢ"
  - "&f➥ &r&7Right click to &f&nsᴇʟʟ"

pricesModifier:
  - permission: "zshop.prices.vip"
    type: SELL
    modifier: 1.5 # Multiplie sell price by x1.5 (+50%, 10 * 1.5 = 15)
  - permission: "zshop.prices.eternal"
    type: SELL
    modifier: 2.0 # Multiplie sell price by x2.0 (+100%, 10 * 2.0 = 20)
  - permission: "zshop.prices.legend.buy"
    type: BUY
    modifier: 0.9 # Multiplie buy price by x0.9 (-10%, 10 * 0.9 = 9)
  - permission: "zshop.prices.legend.sell"
    type: SELL
    modifier: 3.0 # Multiplie sell price by x3.0 (+200%, 10 * 3.0 = 30)